### PR TITLE
Not my code, just injected some from the savior of our souls @Skylortrexler

### PR DESCRIPTION
**Pull request by Lyapsus**

### CODE REVIEW

**Comment by xhmr** [comment]
How to build that?

**Comment by Lyapsus** [comment]
Oh so sorry forgot to release it :)
I'm gonna do it today or maybe tomorrow but u can follow this official guide: fabricmc.net/wiki/tutorial:setup

**Comment by Draylar** [comment]
I can merge and release tonight~

**Comment by xhmr** [comment]
@Draylar that would be great, I can't wait! <3

**Comment by Lyapsus** [comment]
Oh u know we have some problems even with this code

**Comment by Lyapsus** [comment]
Oh and also some problems with some object positions while being thrown in the air...

**Comment by xhmr** [comment]
[']

**Comment by Draylar** [comment]
Released, thank you Skylortrexler and Lyapsus for the help. I noticed a weird snapping issue with blocks landing on the ground, but I'm not sure if that's new or not. I don't have enough time to fix it right now, but I might be able to in the next few days.

**Pull request merged**
