### PR TITLE
Updated to 21w37a

### PR DESCRIPTION
**Pull request by spjoes**
I updated the mod to 1.17 back when that came out and im back! This time just a Fabric API version bump. Not too much.

### CODE REVIEW

**Comment by keatit71** [comment]
Is there a version for 1.17.1 or is that never gonna get an update?

**Comment by spjoes** [comment]
> Is there a version for 1.17.1 or is that never gonna get an update?

The 1.17 version that I did not that long ago still works great on 1.17.1 without an update. Same for this 21w37a release still works great on 21w40a

**Comment by Draylar** [comment]
Sorry, forgot to merge this! I will merge & release tomorrow, please bump if I forget😆

**Comment by Draylar** [comment]
Thanks for your contributions as always!

**Pull request merged**
